<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tag;
use AppBundle\Repository\Contract\SqlCountable;
use AppBundle\Repository\Contract\SqlProductSearchable;
use Doctrine\ORM\Query\Expr;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository implements SqlCountable, SqlProductSearchable
{
    public function total($criteria = []): int
    {
        $queryBuilder = $this->createQueryBuilder('p');
        return $queryBuilder->select('count(p.id)')->getQuery()->getSingleScalarResult();
    }

    public function searchByTags(array $tags)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->innerJoin('p.tags', 't')
            ->where('t.name IN (:tags)')
            ->setParameters([
                'tags' => $tags,
            ]);

        return $queryBuilder->getQuery()->getResult();
    }
}
