<?php

namespace AppBundle\Repository;

use AppBundle\Repository\Contract\SqlCountable;
use Countable;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository implements SqlCountable
{
    public function total($criteria = []): int
    {
        $queryBuilder = $this->createQueryBuilder('t');
        return $queryBuilder->select('count(t.id)')->getQuery()->getSingleScalarResult();
    }
}
