---
version: "3.7"
services:
    # mySQL database image
    mysql:
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # Developer Adminer simillar to phpMyAdmin (developer's tool)
    adminer:
        image: adminer
        restart: on-failure
        env_file:
            - .env
        ports:
            - "${ADMINER_PORT}:8080"

    # http proxy server nginx
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - ./api/web/:/usr/src/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./cache/:/var/cache/nginx
        env_file:
            - .env
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php

    # The php container custome Dockerfile build
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
        volumes:
            - ./api/:/usr/src/api
        #user: ${LOCAL_USER} # check your uid by running `id` command mine is 1000
