app:
    resource: "@AppBundle/Controller/"
    type: annotation

products:
    type: rest
    resource: AppBundle\Controller\ProductsController

products_post:
    path: /products
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\ProductsController:postProductsAction
        _format: json

products_tag_post:
    path: /products/{product}/tag
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\ProductsController:postProductTagAction
        _format: json

tags:
    type: rest
    resource: AppBundle\Controller\TagsController

tags_post:
    path: /tags
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\TagsController:postTagsAction
        _format: json
